wandb:
  entity: null
  project: pokemon
  group: null
env:
  gb_path: environment/red.gbc
  state_dir: environment/states
  override_init_state: null
  init_from_last_ending_state: true
  interactive_mode: true
  record_replays: true
  headless: false
  video_dir: video
  emulator_delay: 11
  action_freq: 24
  save_video: false
  fast_video: false
  n_record: 10
  perfect_ivs: true
  auto_flash: false
  disable_wild_encounters: true
  auto_teach_cut: true
  auto_use_cut: true
  auto_use_surf: true
  auto_teach_surf: true
  auto_use_strength: true
  auto_teach_strength: true
  auto_solve_strength_puzzles: true
  auto_remove_all_nonuseful_items: false
  auto_pokeflute: true
  auto_next_elevator_floor: true
  skip_safari_zone: false
  infinite_safari_steps: false
  insert_saffron_guard_drinks: false
  infinite_money: true
  infinite_health: true
  animate_scripts: true
agent:
  llm_provider: grok
  model_name: grok-3-mini
  max_tokens: 2048
  temperature: 0.7
  grok_on: true
